version: '2'
services:
  app:
    build: .
    environment:
      - GNR_URL=http://gnresolver:9001/api/
      - CODECLIMATE_REPO_TOKEN
    volumes:
      - .:/app
    depends_on:
      - gnresolver
  gnresolver:
    image: gnames/gnresolver-dev:6e2c66
    environment:
      RACK_ENV: development
      DB_HOST: pg
      DB_DATABASE: development
      DB_USER: postgres
      DB_USER_PASS: ""
    command: bin/docker-startup.sh
    depends_on:
      - pg
  pg:
    image: postgres:9.6
